Vagrant.configure("2") do |config|
    config.vm.box = "cbednarski/ubuntu-1604"
    config.vm.network "private_network", ip: "192.168.2.11"
    config.vm.provision "shell", path: "scripts/install_consul.sh", run: "always"
    config.vm.provision "shell", path: "scripts/install_vault.sh", run: "always"
end
